# Generated by Django 4.2.10 on 2024-03-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='pong.tournament'),
        ),
    ]
